import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
const poppins = Poppins({
  weight:['300','400','500','600','700'],
  subsets:['latin-ext']
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mini-ecomerce",
  description: "Generated by create next app",
};

export default function AuthRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={poppins.className}>
        {children}
      </body>
    </html>
  );
}
