import type { Metadata } from "next";
import { Poppins } from "next/font/google";

const poppins = Poppins({
	weight: ["300", "400", "500", "600", "700"],
	subsets: ["latin-ext"],
});

export const metadata: Metadata = {
	title: "Mini-ecomerce",
	description: "Generated by create next app",
};

export default function AuthRootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
    <div className={poppins.className}>
      {children}
    </div>
	);
}
